name: Deploy

on:
  workflow_run:
    workflows: ["Java CI with Gradle"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "notizzettel-web-anwendung"
          heroku_email: "s0569216@htw-berlin.de"


